---
version: 2
multicolumn: true
web-width: 300px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Untitled design/Untitled design.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/78218/articles/384769/master/file/figures/Untitled%20design/Untitled%20design.png"
    folder_url: "/users/78218/articles/384769/master/folder/figures/Untitled design"
